### PR TITLE
fix(core): import FormStates to checkbox

### LINKED ISSUE #3325: typing of state property for checkbox inconsistent with other form controls
https://github.com/SAP/fundamental-ngx/blob/4281e1d43f552c0dbb662bf1d4ad1bd0bbcb8356/libs/core/src/lib/form/form-control/form-control.directive.ts#L23

This causes a problem with strict template checks enabled in Angular.

Furthermore, the FormStates type should be aligned with:
https://github.com/SAP/fundamental-ngx/blob/34a990401692f5c4dbcfb8cbf3ccac886bb5443c/libs/core/src/lib/checkbox/checkbox/checkbox.component.ts#L66

Allowed values are different there.

### PR DESCRIPTION
**Pull request by mikerodonnell89**
Closes #3325

### CODE REVIEW

File: libs/core/src/lib/checkbox/checkbox/checkbox.component.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ import { Platform } from '@angular/cdk/platform';
 import { LIST_ITEM_COMPONENT, ListItemInterface, compareObjects, KeyUtil, ContentDensityService } from '@fundamental-ngx/core/utils';
 import { SPACE } from '@angular/cdk/keycodes';
 import { Subscription } from 'rxjs';
+import { FormStates } from '@fundamental-ngx/core/shared';
```
Comment (aberikashvili) [inline libs/core/src/lib/checkbox/checkbox/checkbox.component.ts:23]: Please rearrange imports

**Review by N1XUS — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]
