### PR TITLE
fix(fn): show selected option label in select

### LINKED ISSUE #8138: Fiori Next: Select - Renders Value instead of Option Label
Using internal values within a select component. The Options render the displayed label correctly.
Once an option is selected the select shows the internal value instead of the option label

image

```
<fn-select placeholder="Select a Parent Company" class="w-100" [(value)]="parentCompany"(ngModelChange)="onParentChanged($event)">
  <li fn-option *ngFor="let partner of partners" [value]="partner.peerId">{{ partner.displayName }}</li>
</fn-select>
```

Also tried binding with [(ngModel)].  

Version: 0.34.3

### PR DESCRIPTION
**Pull request by shrvr**
## Related Issue(s)

closes #8138

## Description

Added [label] property to fn-option.

### Before:
Was showing value of selected option in input-field.
image
image

### After:
image
image

### CODE REVIEW

File: libs/fn/src/lib/select/option/option.component.ts [hunk 1]
```diff
@@ -56,6 +56,13 @@ export class OptionComponent implements OnDestroy, FocusableOption {
     /** Whether this option is hidden */
     hidden = false;
 
+    /**
+     * The displayed value of the option. It shows the selected option in the select's trigger.
+     */
+    get viewValue(): string {
+        return (this.elementRef.nativeElement.textContent || '').trim();
```
Comment (N1XUS) [inline libs/fn/src/lib/select/option/option.component.ts:63]: Not really a fan of this solution. Text content may change whenever developer wants, yet with this approach those changes won't be reflected. Take a look at core's select implementation. There's option to pass custom templateRef for rendering the selected value. Another option would be to use structural directive for the title, and return it's templateRef for rendering

```html
<fn-select placeholder="Select an option" label="Standard Selector">
    <li fn-option *ngFor="let option of options" [value]="option.value">
        <span *fnSelectTitle>{{ option.title }}</span>
    </li>
</fn-select>
```

File: libs/fn/src/lib/select/select.component.ts [hunk 2]
```diff
@@ -171,9 +191,11 @@ export class SelectComponent implements AfterContentInit, OnDestroy, ControlValu
         this.options.forEach((option) => {
             option === clickedOption ? (option.selected = true) : (option.selected = false);
         });
-        this.value = clickedOption.value;
+        clickedOption && this._selectionModel.select(clickedOption);
+        this.value = this.selected.value;
         this.hideMenu();
         this._cdRef.detectChanges();
+        console.log(this._selectionModel.selected);
```
Comment (N1XUS) [inline libs/fn/src/lib/select/select.component.ts:198]: Please remove console.log

**Review by N1XUS — CHANGES_REQUESTED** [review]

File: libs/fn/src/lib/select/select.component.html [hunk 3]
```diff
@@ -18,8 +18,8 @@
         [cdkConnectedOverlayOrigin]="trigger"
         [cdkConnectedOverlayOpen]="opened && !_optionsListEmpty"
     >
-        <ul [style.width.px]="_selectWidth" aria-label="Select menu" fnSelectMenu #menu>
+        <div [style.width.px]="_selectWidth" aria-label="Select menu" fnSelectMenu #menu>
```
Comment (mikerodonnell89) [inline libs/fn/src/lib/select/select.component.html:21]: Assuming the original syntax for the options (using an `li`) can be used, I think we would want to keep this as a `ul`

**Review by mikerodonnell89 — COMMENTED** [review]
I think it would be best to keep the original syntax so there would be no breaking changes, is changing it necessary?

File: libs/docs/fn/select/examples/select-example/select-semantic-example.component.html [hunk 4]
```diff
@@ -1,7 +1,7 @@
 <h4>Positive state</h4>
 <div style="width: 200px">
     <fn-select placeholder="Select an option" label="Standard Selector" state="positive" #selectSemanticPositive>
-        <li fn-option *ngFor="let option of options" [value]="option">{{ option }}</li>
+        <fn-option *ngFor="let option of options" [value]="option" [label]="option"></fn-option>
```
[the remark this answers is not in the document]
Comment (shrvr) [reply libs/docs/fn/select/examples/select-example/select-semantic-example.component.html:4]: Yes, still it can be used.

File: libs/fn/src/lib/select/select.component.html (hunk 3 above)
Comment (mikerodonnell89) [reply libs/fn/src/lib/select/select.component.html:21]: I think it is more important that the rendered template has a `ul` with direct `li` descendants, otherwise we have invalid HTML. Accessibility tools need this `ul` `li` relationship to work properly.

File: libs/fn/src/lib/select/option/option.component.ts [hunk 5]
```diff
@@ -45,6 +45,9 @@ export class OptionComponent implements OnDestroy, FocusableOption {
     @Input()
     selected = false;
 
+    @Input()
```
Comment (platon-rov) [inline libs/fn/src/lib/select/option/option.component.ts:48]: typedoc.

File: libs/fn/src/lib/select/select.component.html (hunk 3 above)
Comment (N1XUS) [reply libs/fn/src/lib/select/select.component.html]: @shrvr What you can do to keep the markup intact is to use ContentChildren for the fn-option, and iterate over it inside ul tag and creating own li elements

Comment (N1XUS) [reply libs/fn/src/lib/select/select.component.html]: @mikerodonnell89 we may have issues with both options:
if we keep li[fn-option], then we'll have invalid markup in the template
If we have fn-option, we'll introduce a breaking change, yet, markup will be valid.

File: libs/fn/src/lib/select/option/option.component.ts [hunk 6]
```diff
@@ -56,6 +60,14 @@ export class OptionComponent implements OnDestroy, FocusableOption {
     /** Whether this option is hidden */
     hidden = false;
 
+    /**
+     * @hidden
+     * The displayed value of the option. Used when label not passed by user. e.g. <li fn-option [value]='Apple'> Apple </li>
+     */
+    get _viewValue(): string {
```
Comment (platon-rov) [inline libs/fn/src/lib/select/option/option.component.ts:67]: We can enhance this to `return this.label ?? this.elementRef...` to remove check `option.label ? option.label : option._viewValue` in `SelectComponent`.

**Review by InnaAtanasova — APPROVED** [review]

**Review by N1XUS — APPROVED** [review]
