### PR TITLE
fix: programmatically click product menu item on space/enter and add keyboard arrow navigation

### LINKED ISSUE #2899: Accessibility inconsistency: Product Switch Keyboard Interaction
According to Fiori Keyboard Interaction Guideline: https://wiki.wdf.sap.corp/wiki/display/Acc/Fiori+Keyboard+Interaction?preview=/1842806926/1867396960/Fiori%20Keyboard%20Interaction%20(untagged).pdf
[Enter-Key] and [Space-Key] should select current focussed element, trigger action.

In current implementation, [Enter-Key] and [Space-Key] does nothing.

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #2899, #2896 

wrong issue number on the branch name

### CODE REVIEW

File: libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts [hunk 1]
```diff
@@ -92,4 +108,67 @@ export class ProductSwitchBodyComponent implements OnInit {
             this.listMode = window.innerWidth < 776;
         }
     }
+
+    /** @hidden */
+    private handleNoListKeydown(event: KeyboardEvent): void {
```
Comment (InnaAtanasova) [inline libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts:113]: should have an `_` since it's private

File: libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts [hunk 2]
```diff
@@ -92,4 +108,67 @@ export class ProductSwitchBodyComponent implements OnInit {
...
+        const target = (<HTMLElement>event.target);
```
Comment (InnaAtanasova) [inline libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts:114]: do you need the ( )?

File: libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts [hunk 3]
```diff
@@ -92,4 +108,67 @@ export class ProductSwitchBodyComponent implements OnInit {
...
+            if (target.nextElementSibling && target.nextElementSibling.nextElementSibling &&
+                target.nextElementSibling.nextElementSibling.nextElementSibling &&
+                target.nextElementSibling.nextElementSibling.nextElementSibling.nextElementSibling) {
+                (<HTMLElement>target.nextElementSibling.nextElementSibling.nextElementSibling.nextElementSibling).focus();
+            }
+        }
+        if (KeyUtil.isKey(event, 'ArrowUp')) {
+            if (target.previousElementSibling && target.previousElementSibling.previousElementSibling &&
+                target.previousElementSibling.previousElementSibling.previousElementSibling &&
+                target.previousElementSibling.previousElementSibling.previousElementSibling.previousElementSibling) {
```
Comment (InnaAtanasova) [inline libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts:141]: Can we simplify these if statements?

File: libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts [hunk 4]
```diff
@@ -92,4 +108,67 @@ export class ProductSwitchBodyComponent implements OnInit {
...
+                    .previousElementSibling).focus();
+            }
+        }
+    }
+
+    /** @hidden */
+    private handleNoListLessThanSeven(event: KeyboardEvent): void {
+        const target = (<HTMLElement>event.target);
+        if (KeyUtil.isKey(event, 'ArrowDown')) {
+            if (target.nextElementSibling && target.nextElementSibling.nextElementSibling &&
```
Comment (salarenko) [inline libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts:152]: What have you done 😆 
Please go recursive on that, or maybe there is a way to get all of the nodes of the parent and then easily get the desired node from the collection.

**Review by salarenko — CHANGES_REQUESTED** [review]

File: libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts (hunk 4 above)
Comment (mikerodonnell89) [reply libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts:152]: Re: this vs. recursive, I think this is about as straightforward as it gets but ok

**Review by salarenko — APPROVED** [review]

**Review by JKMarkowski — APPROVED** [review]
Works well for me. Good Job!
