### PR TITLE
fix: (Core) mirror image multi-input value-help icon when dir="rtl"

### LINKED ISSUE #4871: MultiInput: In RTL mode filter icon is showing wrong.
Description: In RTL mode filter icon is showing wrong. 

Expected: Filter icon should display properly in RTL mode

Screenshot: 

image

expected:
image

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #4871

### CODE REVIEW

**Review by InnaAtanasova — APPROVED** [review]

File: libs/core/src/lib/multi-input/multi-input.component.ts [hunk 1]
```diff
@@ -289,6 +294,10 @@ export class MultiInputComponent implements
         if (this.dropdownValues) {
             this.displayedValues = this.dropdownValues;
         }
+        this._subscriptions.add(this._rtlService.rtl.subscribe(isRtl => {
+            this._dir = isRtl ? 'rtl' : 'ltr';
+            this.buildComponentCssClass();
+        }));
```
Comment (Betrozov) [inline libs/core/src/lib/multi-input/multi-input.component.ts:300]: since _rtlService is optional
```suggestion
        if (this._rtlService) {
            this._subscriptions.add(this._rtlService.rtl.subscribe(isRtl => {
                this._dir = isRtl ? 'rtl' : 'ltr';
                this.buildComponentCssClass();
            }));
        }
```

or remove `@Optional()` from `@Optional() private _rtlService: RtlService`

**Review by Betrozov — CHANGES_REQUESTED** [review]

**Comment by Betrozov** [comment]
please fix netlify

**Review by Betrozov — CHANGES_REQUESTED** [review]
https://github.com/SAP/fundamental-ngx/pull/5008#pullrequestreview-626281073
