### PR TITLE
fix: pagination RTL idea

### LINKED ISSUE #1967: Defect hunting Feb14
- [x] Keyboard service used in tabs is not really supported in RTL mode. The ArrowKeys should also behave inversely. - JEDRZEJ

- [x] All browsers: Table needs new checkbox - STEFANO 
Screen Shot 2020-02-14 at 10 02 53 AM

- [x] All browsers: Fix typo should say without seconds - TYPO - INNA
Screen Shot 2020-02-14 at 10 10 07 AM

- [x] Pagination on RTL - Mike
Screen Shot 2020-02-14 at 10 20 55 AM

- [x] Scroll Spy arrow direction for RTL - Jedrzej
Screen Shot 2020-02-14 at 10 21 28 AM

- [x] All browsers: Add rtf for collapsed side nav - GRACJAN
Screen Shot 2020-02-14 at 10 16 04 AM

### PR DESCRIPTION
**Pull request by mikerodonnell89**
#### Please provide a link to the associated issue.

Closes #1967 

#### Please provide a brief summary of this pull request.

Simply using `dir="rtl"` won't flip the array of numbers presented in the `*ngFor`.  Here I'm using the RtlService and forcing `dir="ltr"` and reversing the array using a pipe.  This feels code-smelly so I'd love to get some other opinions

### Before:
image

### After:
firefox

ie11

### CODE REVIEW

File: libs/core/src/lib/pagination/pagination.component.ts [hunk 1]
```diff
@@ -132,11 +154,22 @@ export class PaginationComponent implements OnChanges {
...
+        return {
             totalItems: this.totalItems,
             currentPage: this.currentPage,
             itemsPerPage: this.itemsPerPage
         };
-        return retVal;
+    }
+
+    /** @hidden */
+    private refreshPages() {
```
Comment (JKMarkowski) [inline libs/core/src/lib/pagination/pagination.component.ts]: privates with `_` prefix

File: libs/core/src/lib/pagination/pagination.component.ts [hunk 2]
```diff
@@ -132,11 +154,22 @@ export class PaginationComponent implements OnChanges {
      * the total number of items, the current page, and the number of items per page.
      */
     getPaginationObject() {
```
Comment (JKMarkowski) [inline libs/core/src/lib/pagination/pagination.component.ts]: Please add returned type.

File: libs/core/src/lib/pagination/pagination.component.ts (hunk 1 above)
Comment (JKMarkowski) [reply libs/core/src/lib/pagination/pagination.component.ts]: Please add returned type.

File: libs/core/src/lib/pagination/pagination.component.html [hunk 3]
```diff
@@ -1,34 +1,48 @@
...
+            <a
+                class="fd-pagination__link"
+                tabindex="0"
+                role="button"
+                (keypress)="onKeypressHandler(page, $event)"
+                (click)="goToPage(page, $event)"
+                *ngIf="page !== -1; else more"
+                [attr.aria-selected]="currentPage === page"
+                >{{ page }}</a
+            >
```
Comment (JKMarkowski) [inline libs/core/src/lib/pagination/pagination.component.html]: This is really weird syntax
