### PR TITLE
fix(core): fix avatar image loading

### LINKED ISSUE #13931: [BUG] Avatars are re-fetched infinitely
Very high prio bug, 
In my component i have only put
<fd-avatar image="/images/jira.svg" size="s" [contain]="true" [transparent]="true" />

This image is re-fetched infinitely (happens only when VPN is turned on)

Image

since version 0.59.1

### PR DESCRIPTION
**Pull request by droshev**
fix avatar image loading

fixes #13931

### CODE REVIEW

File: libs/core/avatar/avatar.component.ts
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: This can be removed when you get rid of the signal lines 274-277

Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: This signal can be replaced by `'[style.background-image]': 'bgImage()'` binding in the host. It now unnecessarily triggers change detection.

File: libs/core/avatar/avatar.component.ts [hunk 1]
```diff
@@ -209,6 +209,15 @@ export class AvatarComponent {
     /** @hidden Stored random color accent to prevent regeneration */
     private readonly _randomColorAccent = signal<ColorAccent>(getRandomColorAccent());
 
+    /** @hidden Track the currently loading/loaded image URL to prevent duplicate requests */
+    private _currentImageUrl: string | null = null;
+
+    /** @hidden Track if an image load is in progress to prevent duplicate requests */
+    private _isLoadingImage = false;
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: Please double check but I think this is redundant and the whole logic can exist without it. The `_isLoadingImage` flag is redundant since the effect already prevents re-calling `_verifyImageUrl` for the same URL.
 
Why it's safe:
 
The effect's `_currentImageUrl !== imageValue` check already prevents duplicate loads for primary images
The `_loadedImageCache` handles re-use of previously loaded images
Backup images are only loaded once per error, so no duplicate risk

File: libs/core/avatar/avatar.component.ts [hunk 2]
```diff
@@ -224,10 +233,17 @@ export class AvatarComponent {
         effect(() => {
             const imageValue = this.image();
             if (imageValue) {
-                this._imageLoaded.set(false);
-                this._shouldShowDefaultIcon.set(false); // Reset default icon flag
-                this._verifyImageUrl(imageValue, this._onErrorCallback.bind(this));
+                // Only reset loaded state if the URL actually changed
+                if (this._currentImageUrl !== imageValue) {
+                    this._imageLoaded.set(false);
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts:232]: this can be removed if you get rid of `_imageLoaded`

File: libs/core/avatar/avatar.component.ts [hunk 3]
```diff
@@ -308,20 +324,38 @@ export class AvatarComponent {
...
     /** @hidden */
     private _verifyImageUrl(srcValue: string, onErrorCallback: () => void): void {
-        const newBgImage = `url(${srcValue})`;
+        // Check if this URL was previously loaded successfully (component-level cache)
+        if (this._loadedImageCache.has(srcValue)) {
+            // Image was loaded before, reuse it
+            this._setBgImage(srcValue);
+            this._imageLoaded.set(true);
+            this._currentImageUrl = srcValue;
+            this._isLoadingImage = false;
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: this can be removed if you get rid of `_imageLoaded`

File: libs/core/avatar/avatar.component.ts [hunk 4]
```diff
@@ -308,20 +324,38 @@ export class AvatarComponent {
...
+            return;
+        }
 
-        // Don't load the same image if it's already loaded successfully
-        if (this.bgImage() === newBgImage && this._imageLoaded()) {
+        // Prevent duplicate requests if this URL is already being loaded
+        if (this._isLoadingImage && this._currentImageUrl === srcValue) {
             return;
         }
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: this can be removed if you get rid of `_imageLoaded`

File: libs/core/avatar/avatar.component.ts [hunk 5]
```diff
@@ -308,20 +324,38 @@ export class AvatarComponent {
...
 
+        // Track the current image URL and loading state
+        this._currentImageUrl = srcValue;
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts:324]: this can be removed if you get rid of `_imageLoaded`

File: libs/core/avatar/avatar.component.ts [hunk 6]
```diff
@@ -308,20 +324,38 @@ export class AvatarComponent {
...
+        this._isLoadingImage = true;
+
         const img = new Image();
         img.onload = () => {
             // Only set background if image loads successfully
             this._setBgImage(srcValue);
             this._imageLoaded.set(true);
+            this._isLoadingImage = false;
```
Comment (InnaAtanasova) [inline libs/core/avatar/avatar.component.ts]: this can be removed if you get rid of `_imageLoaded`

File: libs/core/avatar/avatar.component.ts (hunk 2 above)
Comment (droshev) [reply libs/core/avatar/avatar.component.ts:232]: `_imageLoaded` prevents the label effect from generating new abbreviations when an
  image is already successfully loaded.
