### PR TITLE
fix: (Core) implement and demonstrate wizard in a dialog

### LINKED ISSUE #4012: Support Wizard in Modal Dialog for NGX
Already opened for Styles Library ([Link](https://github.com/SAP/fundamental-styles/issues/1941))

As a Fundamental Library user, I would like to have the wizard also displayed in a modal dialog. Especially useful when there aren't so much steps and content.

Should look and behave like in Fiori 3.

[Cloud Platform Design System Specification](https://sap.frontify.com/document/222581#/creation/wizard)
[Demo Kit Example](https://sapui5.hana.ondemand.com/#/entity/sap.m.Wizard/sample/sap.m.sample.WizardSingleStep)

### PR DESCRIPTION
**Pull request by mikerodonnell89**
#### Please provide a link to the associated issue.

fixes #4012 

#### Please provide a brief summary of this pull request.

Implements and demonstrates wizard in a dialog

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

File: libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts [hunk 1]
```diff
@@ -19,11 +20,24 @@ import { DialogRef } from '../../dialog/utils/dialog-ref.class';
...
+        private _elRef: ElementRef,
         @Optional() public dialogConfig: DialogConfig,
         @Optional() public dialogRef: DialogRef
     ) {}
+
+    /** @hidden */
+    ngAfterContentInit(): void {
+        if (this.wizard) {
+            this._elRef.nativeElement.style.paddingTop = '0px';
+            this._elRef.nativeElement.style.paddingBottom = '0px';
```
Comment (Betrozov) [inline libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts:40]:
```suggestion
            const style = this._elRef.nativeElement.style;
            style.paddingTop = '0px';
            style.paddingBottom = '0px';
```

File: libs/core/src/lib/wizard/wizard.component.html [hunk 2]
```diff
@@ -1,7 +1,7 @@
 <section class="fd-wizard">
     <ng-content select="fd-wizard-navigation"></ng-content>
     <div
-        class="fd-wizard-container-wrapper"
+        [ngClass]="{'fd-wizard-container-wrapper': appendToWizard}"
```
Comment (Betrozov) [inline libs/core/src/lib/wizard/wizard.component.html:4]:
```suggestion
        [class.fd-wizard-container-wrapper]="appendToWizard"
```

**Review by Betrozov — CHANGES_REQUESTED** [review]

**Comment by Betrozov** [comment]
@mikerodonnell89 all these comments are related to this PR?

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 all these 62 comments are related to this PR?

Hmm... maybe this is a side effect of changing our default branch to 'main' while this was a work in progress?  I am not seeing any unintended code changes in the diff

**Comment by Betrozov** [comment]
> > @mikerodonnell89 all these 62 comments are related to this PR?
> 
> Hmm... maybe this is a side effect of changing our default branch to 'main' while this was a work in progress? I am not seeing any unintended code changes in the diff

Could you try to fix it?

**Comment by mikerodonnell89** [comment]
> > > @mikerodonnell89 all these 62 comments are related to this PR?
> > 
> > 
> > Hmm... maybe this is a side effect of changing our default branch to 'main' while this was a work in progress? I am not seeing any unintended code changes in the diff
> 
> Could you try to fix it?

I'd have to rebase and fix conflicts on all these old commits which I think would be a waste of time

**Review by InnaAtanasova — COMMENTED** [review]
Issue 1, steps to reproduce:
- complete all steps and reach the Preview Page
Screen Shot 2021-01-06 at 4 58 12 PM

- click the `Previous Step` button in the footer. The steps are stacked even if there's enough space to fit them:
Screen Shot 2021-01-06 at 4 58 19 PM

**Comment by JKMarkowski** [comment]
> > > > @mikerodonnell89 all these 62 comments are related to this PR?
> > > 
> > > 
> > > Hmm... maybe this is a side effect of changing our default branch to 'main' while this was a work in progress? I am not seeing any unintended code changes in the diff
> > 
> > 
> > Could you try to fix it?
> 
> I'd have to rebase and fix conflicts on all these old commits which I think would be a waste of time

@mikerodonnell89 I guess you checked out from some old branch, because almost half of commits is from november.

File: libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts [hunk 3]
```diff
@@ -19,11 +20,25 @@ import { DialogRef } from '../../dialog/utils/dialog-ref.class';
         '[class.fd-dialog__body--no-vertical-padding]': '!dialogConfig.verticalPadding'
     }
 })
-export class DialogBodyComponent {
+export class DialogBodyComponent implements AfterContentInit {
+
+    /** @hidden */
+    @ContentChild(WizardComponent)
```
Comment (JKMarkowski) [inline libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts:26]: Consider adding `{ descendants: true }`

Comment (mikerodonnell89) [reply libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts:26]: I do not anticipate an instance of the wizard not being a direct descendant of the dialog body, but I will add this just in case

**Comment by colinjoy** [comment]
Hi,

thank you for work on adding this new capability to fundamentals-ngx!

I did a cursory review of the sample found in the deploy-4218 preview and compared it to the ui5 sample implementation (which matches the desired design target).

Since I could not create a local dev environment for fundamentals yet (ng version/dependency resolution problems), I could not establish which of these issues are mere matters of configuration / using the correct classes and properties or whether changes to the wizard or dialog components would be needed. you may be able to determine this more quickly.

In either case, it would be nice if the sample would more closely resemble the desired target design, as people tend to copy from examples.

Best regards,
Colin

On the left side, you see a screenshot of the ui5 implementation.
The right side shows the sample from this PR.

4218-wizard-in-dialog-sample

https://www.figma.com/file/AGOECvYDcaeciA3RPBXPIY/Fundamentals-Wizard-Dialog?node-id=0%3A1

1. Scroll behaviour: Only the body content should overflow. Step navigation should remain in place when scrolling content. Overflow should only occur when content doesn't fit the available space, here it appears that the height is not calculated correctly
2. Dialog title for wizard should not display a bottom border / shadow
3. Title font size appears does not match sample
4. Step navigation margin/padding does not match spec/sample
5. It would be preferred if the example could demonstrate use of numbers for steps (90% use case), not icons.
6. Footer should be of the "floating" variant, e.g. page footer
7. Vertical margins between title, message strip and text are missing - example should implement correct default margins / line heights
8. Wizard should not feature [x] button in top right corner of dialog

**Comment by mikerodonnell89** [comment]
@colinjoy thank you for your detailed comment.  I was able to update a few of the things you pointed out in this PR, but the scroll behavior, as well as changes to the header and footer will require some refactoring of the wizard and the dialog components so we will address that in this ticket: https://github.com/SAP/fundamental-ngx/issues/4342

**Review by Betrozov — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]
