### PR TITLE
fix(platform): add ability to pass action to approval flow component

### LINKED ISSUE #7001: bug: Approval flow(platform) - ability to specify action after adding new approver without saving
#### Below are steps to reproduce:
1. Have 2 approvers already in the approval flow.
2. Click Edit and add 1 new approver. Do NOT click Save yet.
3. Click + to add 1 parallel node. At this point, we don't want to the user to add parallel node as it caused many issues in our app. Sourcing don't support adding parallel nodes.
- Please see video below to clarification.

https://user-images.githubusercontent.com/86618211/139108640-076587ee-6745-4b43-b4ea-690176b24bbf.mov

#### Is there anything else we should know?
- We cannot call rest API until the user clicks Save button. There is no way for us to restrict the user from adding parallel/add before a node.

#### Solution
1. Add ability to pass custom action which will be invoked every time when user adds new node
2. Add ability to `enable / disable` and `show / hide` approval flow control buttons (save, exit)

### PR DESCRIPTION
**Pull request by aberikashvili**
## Related Issue(s)

closes #7001 

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

### CODE REVIEW

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts [hunk 1]
```diff
@@ -79,6 +92,14 @@ export class PlatformApprovalFlowExampleComponent implements OnDestroy {
         console.log('Node click handler', node);
     }
 
+    afterNodeAdd(node: ApprovalNode): void {
+        const meta = this._approvalFlow._graphMetadata[node.id];
```
Comment (dimamarksman) [inline apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts:96]: Let's define a public method to retrieve node metadata by giving node id instead of touching `_graphMetadata` directly cause underscore means that it is private one

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html [hunk 2]
```diff
@@ -124,3 +127,37 @@ <h4 style="margin-top: 1.5rem; margin-bottom: 1rem">Company</h4>
         [(ngModel)]="sendReminderStatuses"
     ></fd-multi-input>
 </p>
+<p>Disable certain node actions for newly added nodes:</p>
+<div>
+    <p>
+        <input
+            id="disableAddingNodeBefore"
```
Comment (dimamarksman) [inline apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html:134]: id must be unique

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html [hunk 3]
```diff
@@ -124,3 +127,37 @@ <h4 style="margin-top: 1.5rem; margin-bottom: 1rem">Company</h4>
         [(ngModel)]="sendReminderStatuses"
     ></fd-multi-input>
 </p>
+<p>Disable certain node actions for newly added nodes:</p>
```
Comment (dimamarksman) [inline apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html:130]: https://user-images.githubusercontent.com/3263744/142210444-f9858315-0616-4579-86ce-a5ff1aab7da0.mp4

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts (hunk 1 above)
Comment (aberikashvili) [reply apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts:96]: Done

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html (hunk 2 above)
Comment (aberikashvili) [reply apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html:134]: Done

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html (hunk 3 above)
Comment (aberikashvili) [reply apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.html:130]: Done

**Comment by aberikashvili** [comment]
@dimamarksman your comments are addressed, please check again

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts [hunk 4]
```diff
@@ -300,6 +308,10 @@ export class ApprovalFlowComponent implements OnInit, OnDestroy {
             });
     }
 
+    getMetadata(nodeId: string): ApprovalGraphNodeMetadata {
```
Comment (dimamarksman) [inline libs/platform/src/lib/approval-flow/approval-flow.component.ts:311]: let's call it more obvious, e.x `getNodeMetadaById`,
also please add property description comments

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts [hunk 5]
```diff
@@ -90,9 +91,24 @@ export class ApprovalFlowComponent implements OnInit, OnDestroy {
     /** Text label for watchers list */
     @Input() watchersLabel = 'Watchers';
 
+    /** Enables or disables ability to add parallel nodes */
+    @Input() allowAddParallelNodes = true;
+
+    /** Disables save button, save button is enabled by default */
+    @Input() disableSaveButton = false;
```
Comment (platon-rov) [inline libs/platform/src/lib/approval-flow/approval-flow.component.ts:98]: I don't see a request for disabling/enabling the save or exit button in the issue. Where this request come from?

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts (hunk 4 above)
Comment (platon-rov) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:311]: It will be a breaking change, just fyi.

Comment (dimamarksman) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:311]: why breaking change? this is a new method

Comment (platon-rov) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:311]: my miss, sorry, you're right.

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts (hunk 5 above)
Comment (aberikashvili) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:98]: @platon-rov request is coming from @835291 , we had discussion meeting around approval flow

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts (hunk 4 above)
Comment (aberikashvili) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:311]: Done

**Review by platon-rov — APPROVED** [review]

**Review by OleksiyDrozdov — APPROVED** [review]

File: apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts [hunk 6]
```diff
@@ -31,11 +36,25 @@ export class PlatformApprovalFlowExampleComponent implements OnDestroy {
         disableEdit: false,
         disableRemove: false
     };
+    nodeActionsConfigForNewNodes: ApprovalNodeActionsConfig = {
```
Comment (Betrozov) [inline apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts:39]: please add typedoc
please check the whole file

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts [hunk 7]
```diff
@@ -249,6 +265,14 @@ export class ApprovalFlowComponent implements OnInit, OnDestroy {
         this.nodeClick.emit(node);
     }
 
+    _onNodeAdd(node: ApprovalNode): void {
```
Comment (Betrozov) [inline libs/platform/src/lib/approval-flow/approval-flow.component.ts:268]: please add typedoc
please check the whole file

**Review by Betrozov — CHANGES_REQUESTED** [review]

**Review by dimamarksman — APPROVED** [review]

File: libs/platform/src/lib/approval-flow/approval-flow.component.ts (hunk 7 above)
Comment (aberikashvili) [reply libs/platform/src/lib/approval-flow/approval-flow.component.ts:268]: Done

**Review by Betrozov — APPROVED** [review]
