### PR TITLE
fix: (Core) remove wizard padding logic from dialog body component

### LINKED ISSUE #5402: Dialog body has unnecessary wizard component import
Currently the dialog body checks for a wizard component ContentChild and applies some styles if it exists.  At the same time the wizard ascends its nativeElement's parents to check to see if it's in a dialog in order to calculate the height of itself.  We can remove the WizardComponent import from the dialog body and handle the styling logic there in the wizard itself, solving the circular dependency issue

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #5402 

Moves wizard padding logic away from the dialog body to remove circular dependency between components

### CODE REVIEW

File: libs/core/src/lib/wizard/wizard.component.ts [hunk 1]
```diff
@@ -201,6 +201,10 @@ export class WizardComponent implements AfterViewInit, OnDestroy {
         const dialogBody = this._elRef.nativeElement.parentElement;
         let retVal = 0;
         if (dialogBody.tagName.toLowerCase() === 'fd-dialog-body') {
+            const dialogBodyStyle = this._elRef.nativeElement.parentElement.style;
```
Comment (N1XUS) [inline libs/core/src/lib/wizard/wizard.component.ts:204]: This can be done with @Inject(DialogBodyComponent), or with some providers, which might be more feasible here.
After you inject parent component, you can call parent component's method to set additional class to the host, which will apply this styling changes, instead of doing this with JS.

Comment (mikerodonnell89) [reply libs/core/src/lib/wizard/wizard.component.ts:204]: Great suggestion, I will use `@Optional` to inject it into the constructor

File: libs/core/src/lib/wizard/wizard.component.ts [hunk 2]
```diff
@@ -198,14 +204,21 @@ export class WizardComponent implements AfterViewInit, OnDestroy {
 
     /** @hidden */
     private _getDialogOffset(): number {
-        const dialogBody = this._elRef.nativeElement.parentElement;
         let retVal = 0;
-        if (dialogBody.tagName.toLowerCase() === 'fd-dialog-body') {
-            if (dialogBody.querySelector('.' + 'fd-title--h2')) {
-                retVal = dialogBody.querySelector('.' + 'fd-title--h2').offsetHeight;
+        if (this._dialogBodyComponent) {
```
Comment (N1XUS) [inline libs/core/src/lib/wizard/wizard.component.ts:208]: I would do it like this:
`this._dialogBodyComponent.addClass('fd-dialog-body--no-vertical-padding')`
As for height, resizeObserver might help you out with window resize and dynamic content

File: libs/core/src/lib/wizard/wizard.component.ts [hunk 3]
```diff
@@ -198,14 +204,21 @@ export class WizardComponent implements AfterViewInit, OnDestroy {
...
+            const dialogBody = this._dialogBodyComponent.elementRef().nativeElement;
+            if (dialogBody.tagName.toLowerCase() === 'fd-dialog-body') {
+                const dialogBodyStyle = dialogBody.style;
+                dialogBodyStyle.paddingTop = '0';
+                dialogBodyStyle.paddingBottom = '0';
+                dialogBodyStyle.overflowY = 'hidden';
+                if (dialogBody.querySelector('.' + 'fd-title--h2')) {
```
Comment (N1XUS) [inline libs/core/src/lib/wizard/wizard.component.ts:215]: Get element once and set it to some const. Also, no need to contact the string here

File: libs/core/src/lib/wizard/wizard.component.ts (hunk 2 above)
Comment (mikerodonnell89) [reply libs/core/src/lib/wizard/wizard.component.ts:208]: this is actually a property of dialogConfig so I will use that

**Review by InnaAtanasova — APPROVED** [review]
