### PR TITLE
fix: search input observable support and examples

### LINKED ISSUE #631: Observable for search input
See #628 and do that for search input

### PR DESCRIPTION
**Pull request by mikerodonnell89**
fixes #631

### CODE REVIEW

File: docs/modules/documentation/containers/search-input/search-input-docs.component.ts [hunk 1]
```diff
@@ -16,5 +18,15 @@ export class SearchInputDocsComponent {
     searchInputDynamicHtml = searchInputDynHtml;
     searchInputDynamicTs = searchInputDynTs;
 
+    searchInputAsyncHtml = searchInputAsyncHtml;
+    searchInputAsyncTs = searchInputAsyncTs;
+
+    searchInputAsyncData = JSON.stringify([
+        {"text": "Apple", "alertMessage": "Apple Clicked"},
```
Comment (MattL75) [inline docs/modules/documentation/containers/search-input/search-input-docs.component.ts]: single quote plus no need for quotes at all for the field name, no need to format it like real json if you're stringifying

File: docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+@Component({
+    selector: 'fd-search-input-async-example',
+    templateUrl: './search-input-async-example.component.html'
+})
+export class SearchInputAsyncExampleComponent implements OnInit {
+
+    searchTerm: string = '';
+
+    dropdownValues;
```
Comment (MattL75) [inline docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.ts]: type Observable<string[]>

File: docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.ts [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+    getDropdownValues(): Observable<string[]> {
+        return this.http.get<any[]>('./assets/search-input-values.json').pipe(
+            map(data => {
+                data.forEach(fruitObject => {
+                    if (fruitObject.alertMessage) {
+                        fruitObject.callback = (function () {
```
Comment (MattL75) [inline docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.ts]: arrow function
