### PR TITLE
fix(core,platform,btp,cx): migrate remaining Default strategy components to OnPush

### LINKED ISSUE #14039: Audit ChangeDetectionStrategy.Default components for zoneless compatibility
## Problem

Related to #14035 (NgZone removal tracking).

Components using `ChangeDetectionStrategy.Default` rely on zone.js to trigger change detection on every async event (HTTP calls, timers, DOM events). In zoneless Angular 21, these components **won't update automatically** — they need either `OnPush` with explicit `markForCheck()` calls, or signals.

## Scope

**15 files** currently use `ChangeDetectionStrategy.Default` (explicitly set or inherited):

These were found by searching for explicit `ChangeDetectionStrategy.Default` declarations. Additionally, any component that doesn't declare a change detection strategy at all inherits `Default` — those are harder to enumerate but equally affected.

## What to look for

A `Default` strategy component is **safe** if:
- All its template bindings come from signals or observables with `async` pipe
- It has no async state mutations (everything is synchronous input-driven)

A `Default` strategy component **needs fixing** if:
- It mutates class properties in async callbacks (HTTP, timers, event listeners) that are bound in the template
- It relies on parent component CD runs to propagate changes downward

## Suggested fix

For most components in this project, the fix is straightforward:
1. Change to `ChangeDetectionStrategy.OnPush`
2. Add `markForCheck()` where needed, or migrate to signals

This is lower priority than the NgZone and setTimeout audits, since `Default` components will still *mostly* work via parent CD propagation — but they'll have subtle, hard-to-reproduce bugs.

## References

- Parent issue: #14035
- setTimeout/setInterval audit: #14037
- Angular zoneless guide: https://angular.dev/guide/experimental/zoneless

### PR DESCRIPTION
**Pull request by droshev**
migrate remaining Default strategy components to OnPush

fixes #14039

Summary

  Audit and migrate all remaining ChangeDetectionStrategy.Default components to OnPush for zoneless
  compatibility (#14039).

  Changes across 52 files (48 components, 3 specs, 1 base class):

  Core changes (applied to all 48 components):
  - Add ChangeDetectionStrategy.OnPush
  - Replace detectChanges() with markForCheck()
  - Remove standalone: true (default since Angular 19)

  FilterCustomComponent (libs/platform/table/.../filter-custom.component.ts):
  - Migrate from ngDoCheck polling to afterEveryRender — the only component that needed special handling
  because it detects mutations on a plain object passed by reference into a user template
  - Add markForCheck() after emission for OnPush parent notification
  - New spec file with 20 tests covering mutation detection, circular references, filterBy reset, template
  integration, and content density

  Icon Tab Bar (libs/platform/icon-tab-bar/):
  - Remove NgZone.onMicrotaskEmpty dependency from base class and process-type component
  - Replace with afterNextRender for zoneless compatibility
  - Preserve async _selectExtraItem(): Promise<void> signature (no breaking change)

  Affected libraries: core, platform, cdk, btp, cx

  Out of scope (intentionally not changed):

  - setTimeout() → afterNextRender() replacement (tracked in #14037)
  - @HostBinding / @HostListener → host: {} migration (future ticket)
### Review findings addressed

  | Concern | Analysis |
  |---------|----------|
  | OnPush on dialog/message-box containers may regress #12521 (dynamic content not updating) | Low risk. `_attached()` now calls `markForCheck()` on portal content. Child internal state changes are governed by the child's own CD, not the container's. |
  | Redundant `markForCheck()` after `signal.set()` on `@HostBinding` | Not redundant. `@HostBinding` getter is not a signal-reactive context — `markForCheck()` is needed. The CLAUDE.md rule applies to `host: {}` and template bindings only. |
  | Missing `markForCheck()` in `list-navigation-item` after mutating `@HostBinding` props | Not needed. `_handleExpandedChanges()` is only called from `@HostListener` handlers — DOM events automatically trigger CD on OnPush components. |
  | `afterEveryRender` detects mutations one frame later than `ngDoCheck` | Valid but inconsequential. Filter dialog requires user to click "OK" to apply — one-frame delay is imperceptible. |

### CODE REVIEW

File: libs/btp/search-field/src/search-field.component.ts [hunk 1]
```diff
@@ -68,7 +74,10 @@ export class SearchFieldComponent implements AfterViewInit, HasElementRef {
         this._cvaControl.listenToChanges();
         (this._cvaControl.cvaDirective?.ngControl?.valueChanges || of(undefined))
             .pipe(
-                tap((value: string) => (this._value = value)),
+                tap((value: string) => {
+                    this._value = value;
+                    this._cdr.markForCheck();
```
Comment (mikerodonnell89) [inline libs/btp/search-field/src/search-field.component.ts]: I think this component's `focus()` function needs markForCheck too

File: libs/platform/value-help-dialog/components/base-tab/vhd-base-tab.component.ts [hunk 2]
```diff
@@ -1,12 +1,12 @@
...
 
 import { VhdTab } from '../../models';
 
 @Component({
     template: '',
-    standalone: true
+    changeDetection: ChangeDetectionStrategy.OnPush
 })
-// eslint-disable-next-line @angular-eslint/component-class-suffix
+
```
Comment (MariaIDineva) [inline libs/platform/value-help-dialog/components/base-tab/vhd-base-tab.component.ts]: Redundant blank line

File: libs/core/side-navigation/side-navigation.component.ts [hunk 3]
```diff
@@ -76,12 +82,18 @@ export class SideNavigationComponent implements AfterContentInit, AfterViewInit,
...
 
+    /** @hidden */
+    private readonly _cdr = inject(ChangeDetectorRef);
+
+    /** @hidden */
+    private readonly _destroyRef = inject(DestroyRef);
+
     /** @hidden */
     constructor(
         private keyboardService: NestedListKeyboardService,
```
Comment (MariaIDineva) [inline libs/core/side-navigation/side-navigation.component.ts:93]: Maybe inject those outside the constructor for consistency.
