### PR TITLE
fix(platform): simplify class inheritance

### LINKED ISSUE #10709: Platform BaseInput - deprecate input ariaLabel
deprecate input ariaLabel - is it not used or set to anything.

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

closes #10709

## Description
- Removed duplicated properties: `ariaLabelledBy` and `ariaLabelledBy` from `BaseInputComponent`, `BaseSelectComponent`, `BaseListItemComponent`, `SearchFieldComponent`, `SwitchComponent`, `DynamicPageComponent` in `platform` package in favor of same properties from the `BaseComponent` class;
- Simplified long constructor chains with `inject` instead of constructor signature;
- Removed duplicated class properties such as `ChangeDetectorRef`, `ElementRef`, `NgZone`, etc.

BREAKING CHANGE:
- Switch component now uses `ariaLabelledBy` instead of `ariaLabelledby`

### CODE REVIEW

File: libs/cdk/utils/abstract-fd-ngx-class.ts [hunk 1]
```diff
@@ -11,10 +11,10 @@ import { Directive, ElementRef, Input, OnChanges, OnInit } from '@angular/core';
 @Directive()
 export abstract class AbstractFdNgxClass implements OnInit, OnChanges {
     /** @hidden */
-    private _elementRef: ElementRef;
+    @Input() class: string; // user's custom classes
 
     /** @hidden */
-    @Input() class: string; // user's custom classes
+    readonly elementRef = inject(ElementRef);
```
Comment (g-cheishvili) [inline libs/cdk/utils/abstract-fd-ngx-class.ts:17]: Can you add `HasElementRef` interface implements too?

**Review by InnaAtanasova — APPROVED** [review]
