### PR TITLE
fix: make tokenizer/multiinput responsive

### LINKED ISSUE #2018: responsive tokenizer
If the tokens in the tokenizer take up more width than the tokenizer itself, they simply aren't displayed.  We need to hide overflowing tokens and display the text "____ more".  Use the breadcrumb responsive logic as a starting point for how this should work (though this will be simpler).

What's currently happening:
Screen Shot 2020-02-19 at 3 10 39 PM

What we need:
Screen Shot 2020-02-19 at 5 06 08 PM

### PR DESCRIPTION
**Pull request by mikerodonnell89**
#### Please provide a link to the associated issue.

fixes #2018 

#### Please provide a brief summary of this pull request.

Collapse/expand tokens within the tokenizer depending on tokenizer width.  Multi-input should display "____ more" text indicating how many collapsed tokens there are.  Also refactor the breadcrumb responsiveness a little bit.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done

### CODE REVIEW

**Comment by estelaxu3** [comment]
I notice that if I delete the items in tokenizer, the label "x more" doesn't change. If I added 5 items, it will say "5 more" even when I delete everything.
Screen Shot 2020-03-04 at 4 37 13 PM

**Comment by stefanoScalzo** [comment]
dont think we should allow empty tokens, it creates weird spacing

**Comment by mikerodonnell89** [comment]
Depends on https://github.com/SAP/fundamental-styles/pull/775

**Comment by stefanoScalzo** [comment]
Maybe the show all should have our link component? 
Screen Shot 2020-03-18 at 6 24 36 PM

**Comment by stefanoScalzo** [comment]
Also its weird at a certain size the text input disappears
Screen Shot 2020-03-18 at 6 26 24 PM
 might be a styles issue tho

**Comment by mikerodonnell89** [comment]
In order to test this you will need to pull the branch locally and update your `package.json` to use  `fundamental-styles: "^0.8.0-rc.28"` https://www.npmjs.com/package/fundamental-styles/v/0.8.0-rc.28

**Comment by mikerodonnell89** [comment]
We may want to actually merge this branch: https://github.com/SAP/fundamental-ngx/tree/tokenizer-ngOnChanges-classes-merge

After this PR gets merged: https://github.com/SAP/fundamental-ngx/pull/2249

So I'll consider this blocked until then

File: libs/core/src/lib/bar/bar.component.ts [hunk 1]
```diff
@@ -17,59 +17,40 @@ export type BarDesignType = 'header' | 'subheader' | 'header-with-subheader' | '
...
+export class BarComponent implements OnChanges, OnInit, CssClassBuilder {
 
     /** user's custom classes */
-    private _class: string = '';
     @Input()
-    set class(userClass: string) {
-        this._class = userClass;
-        this.buildComponentCssClass();
-    }
+    class: string;
```
Comment (InnaAtanasova) [inline libs/core/src/lib/bar/bar.component.ts:24]: I believe this changes were introduced in https://github.com/SAP/fundamental-ngx/pull/2228

File: libs/core/src/lib/form/form-group/form-group.component.ts [hunk 2]
```diff
@@ -20,28 +20,31 @@ import { CssClassBuilder, applyCssClass } from '../../utils/public_api';
...
     /** Determines if form items should be displayed inline or not
      * Default value is set to false;
      */
-    @Input() set isInline(inline: boolean) {
-        this._isInline = inline;
-        this.buildComponentCssClass();
-    }
+    @Input()
+    isInline: boolean;
+
```
Comment (InnaAtanasova) [inline libs/core/src/lib/form/form-group/form-group.component.ts:32]: These changes are also introduced in https://github.com/SAP/fundamental-ngx/pull/2228

File: libs/core/src/lib/token/tokenizer.component.ts [hunk 3]
```diff
@@ -19,54 +22,138 @@ import { TokenComponent } from './token.component';
...
-export class TokenizerComponent implements AfterViewInit {
+export class TokenizerComponent implements AfterViewInit, AfterContentInit {
 
     /** @hidden */
     @ContentChildren(forwardRef(() => TokenComponent))
     tokenList: QueryList<TokenComponent>;
 
     /** @hidden */
-    @ContentChild(forwardRef(() => FormControlDirective), {static: true})
+    @ContentChild(forwardRef(() => FormControlDirective), {static: false})
```
Comment (InnaAtanasova) [inline libs/core/src/lib/token/tokenizer.component.ts:32]: I believe in Angular 9 the default value of static is false so you don't have to set it.

File: libs/core/src/lib/token/tokenizer.component.ts [hunk 4]
```diff
@@ -19,54 +22,138 @@ import { TokenComponent } from './token.component';
...
     input: FormControlDirective;
 
+    /** @hidden */
+    @ViewChild('tokenizerInner', {static: false})
+    tokenizerInnerEl: ElementRef;
+
+    /** @hidden */
+    @ViewChild('moreElement', {static: false})
```
Comment (InnaAtanasova) [inline libs/core/src/lib/token/tokenizer.component.ts:40]: I believe in Angular 9 the default value of static is false so you don't have to set it.

File: libs/core/src/lib/input-group/input-group-directives.ts [hunk 5]
```diff
@@ -95,7 +95,7 @@ export class InputGroupAddOnDirective extends AbstractFdNgxClass implements Afte
 
     /** @hidden */
     constructor(
-        private elementRef: ElementRef,
+        public elementRef: ElementRef,
```
[the remark this answers is not in the document]
Comment (mikerodonnell89) [reply libs/core/src/lib/input-group/input-group-directives.ts:98]: My linter seems to think I do
Screen Shot 2020-04-06 at 6 08 49 PM

File: libs/core/src/lib/bar/bar.component.ts (hunk 1 above)
Comment (mikerodonnell89) [reply libs/core/src/lib/bar/bar.component.ts:24]: I actually merged that branch in to this branch as this branch depends on it.  So that is why you are seeing all the changes to a bunch of different files

**Comment by mikerodonnell89** [comment]
Should have left this as blocked as it depends on https://github.com/SAP/fundamental-ngx/pull/2228

**Comment by estelaxu3** [comment]
The cozy mode can't be fold into "(x) more" 
Screen Shot 2020-04-07 at 10 44 51 AM

**Comment by mikerodonnell89** [comment]
> The cozy mode can't be fold into "(x) more"
> Screen Shot 2020-04-07 at 10 44 51 AM

this is according to the designs

**Comment by mikerodonnell89** [comment]
> This PR is changing many other files not just Tokenizer/MultiInput. Is it intentional?

A lot of the changes came from #2228 which has now been merged so you should be seeing fewer. There are still some seemingly random changes, like one to breadcrumb, but i did that because the tokenizer and breadcrumb resize logic is very similar.

File: libs/core/src/lib/input-group/input-group-directives.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (InnaAtanasova) [reply libs/core/src/lib/input-group/input-group-directives.ts:98]: oh, it's the constructor! Of course you need public. Sorry, my bad :D

**Comment by InnaAtanasova** [comment]
Screen Shot 2020-04-07 at 4 19 31 PM
Screen Shot 2020-04-07 at 4 18 38 PM
Mutli Input - there is a spacing on the right side of the button

Screen Shot 2020-04-07 at 4 20 14 PM
The focus outline is cut

Screen Shot 2020-04-07 at 4 20 37 PM
For MultiInput I think the button addon should be always visible. Now when you add more tokens it hides.

The Token has cut focus outline:
Screen Shot 2020-04-07 at 4 21 09 PM

Shouldn't clicking on __more button open a dropdown with all Tokens?

File: libs/core/src/lib/form/form-control/form-control.directive.ts [hunk 6]
```diff
@@ -30,51 +29,58 @@ export class FormControlDirective extends AbstractFdNgxClass {
...
+            this.type === 'radio' ? 'fd-radio' : '',
+            this._getElementTag() === 'input' ? 'fd-input' : '',
+            this._getElementTag() === 'textarea' ? 'fd-textarea' : '',
+            this._getElementTag() === 'select' ? 'fd-form-select' : '',
+            this.compact && this._getElementTag() === 'input' ? 'fd-input--compact' : '',
+            this.compact && this._getElementTag() === 'textarea' ? 'fd-textarea--compact' : '',
+            this.compact && this._getElementTag() === 'select' ? 'fd-form-select--compact' : '',
+            this.class
+        ].filter(x => x !== '').join(' ');
+    }
```
Comment (JKMarkowski) [inline libs/core/src/lib/form/form-control/form-control.directive.ts:56]: Can we have some method there?
```suggestion

    buildComponentCssClass(): string {
        return [
            this.state ? 'is-' + this.state : '',
            this._getFormClass(),
            this.compact ? (this._getFormClass() + '--compact') : '',
            this.class
        ].filter(x => x !== '').join(' ');
    }
        
    private _getFormClass(): string {
        let class: string = '';
        switch (this._getElementTag()) {
            case: 'input': 
                class = 'fd-input';
                break;
            case: 'select': 
            ...
        }
    }
```

File: libs/core/src/lib/token/tokenizer.component.ts [hunk 7]
```diff
@@ -94,4 +182,128 @@ export class TokenizerComponent implements AfterViewInit {
...
+                elementWidth = this.elementRef.nativeElement.getBoundingClientRect().width;
+                combinedTokenWidth = this.getCombinedTokenWidth();
+                side === 'right' ? i-- : i++;
+                this.cdRef.markForCheck();
+            }
+        }
+    }
+
+    /** @hidden */
+    expandTokens(): void {
```
Comment (JKMarkowski) [inline libs/core/src/lib/token/tokenizer.component.ts:233]: Can we make it private?

File: libs/core/src/lib/token/tokenizer.component.ts [hunk 8]
```diff
@@ -94,4 +182,128 @@ export class TokenizerComponent implements AfterViewInit {
...
+                this.collapseTokens();
+            } else {
+                this.expandTokens(); // if it's getting bigger, try expanding
+            }
+            this.previousElementWidth = elementWidth;
+        }
+    }
+
+    /** @hidden */
+    collapseTokens(side?: string): void {
```
Comment (JKMarkowski) [inline libs/core/src/lib/token/tokenizer.component.ts:201]: Can we make it private?

File: libs/core/src/lib/token/tokenizer.component.ts [hunk 9]
```diff
@@ -19,54 +22,138 @@ import { TokenComponent } from './token.component';
...
+                this.makeElementVisible(poppedToken.elementRef);
+            }
+            // and then hide any tokens from the left that no longer fit
+            this.collapseTokens('left');
+        }
+    }
+
     /** @hidden */
-    focusTokenElement(event: KeyboardEvent, newIndex: number): HTMLElement {
+    focusTokenElement(event: Event, newIndex: number): HTMLElement {
```
Comment (JKMarkowski) [inline libs/core/src/lib/token/tokenizer.component.ts:156]: Order of methods rules should be followed, take a look [there](https://github.com/SAP/fundamental-ngx/wiki/Code-Contribution-Guideline)

File: libs/core/src/lib/token/tokenizer.component.html [hunk 10]
```diff
@@ -1,7 +1,20 @@
-<div class="fd-tokenizer" tabindex="0" (focus)="tokenizerHasFocus = true" (blur)="tokenizerHasFocus = false;"
+<div class="fd-tokenizer fd-tokenizer--scrollable" tabindex="0" (focus)="tokenizerHasFocus = true" (blur)="tokenizerHasFocus = false;"
         [ngClass]="{'is-focus': tokenizerHasFocus, 'fd-tokenizer--compact': compact}">
-    <div class="fd-tokenizer__inner">
+    <div class="fd-tokenizer__inner" #tokenizerInner>
         <ng-content select="fd-token"></ng-content>
+        <span *ngIf="(moreTokensLeft.length > 0 || moreTokensRight.length > 0) && compact" class="fd-tokenizer-more" #moreElement>
+            <ng-container>{{moreTokensLeft.length + moreTokensRight.length}} more</ng-container>
```
Comment (JKMarkowski) [inline libs/core/src/lib/token/tokenizer.component.html:6]: Can we put some customizable `{{word}}`, instead of `more`?

File: libs/core/src/lib/token/tokenizer.component.html [hunk 11]
```diff
@@ -1,7 +1,20 @@
-<div class="fd-tokenizer" tabindex="0" (focus)="tokenizerHasFocus = true" (blur)="tokenizerHasFocus = false;"
+<div class="fd-tokenizer fd-tokenizer--scrollable" tabindex="0" (focus)="tokenizerHasFocus = true" (blur)="tokenizerHasFocus = false;"
         [ngClass]="{'is-focus': tokenizerHasFocus, 'fd-tokenizer--compact': compact}">
-    <div class="fd-tokenizer__inner">
+    <div class="fd-tokenizer__inner" #tokenizerInner>
         <ng-content select="fd-token"></ng-content>
+        <span *ngIf="(moreTokensLeft.length > 0 || moreTokensRight.length > 0) && compact" class="fd-tokenizer-more" #moreElement>
```
Comment (JKMarkowski) [inline libs/core/src/lib/token/tokenizer.component.html:5]: I'm not sure if it's good idea to depend behaviour on `compact` flag. Maybe let's have another better docummented flag like `collapseTokens: boolean` or something. It would be great to put some dedicated section only for it

Comment (mikerodonnell89) [reply libs/core/src/lib/token/tokenizer.component.html:5]: Are you saying collapseTokens would be an input or somehow behave separately from the compact flag?  The specs make it pretty clear that phones are cozy and don't have "more" text and desktop is compact and does have "more" so I don't think we should deviate from that
