### PR TITLE
fix: (Platform) Add examples in list with long text for accessibility test

### LINKED ISSUE #3487: Accessibility:List: The “unread” information is not conveyed when unread list items are accessed.
Description: The “unread” information is not conveyed when unread list items are accessed. 

Expected: Unread information about list items should be conveyed to the user, when list items are accessed. 

Screenshot: 

image

### LINKED ISSUE #4112: List & List Items (Platform): missing examples
#### Briefly describe your proposal.
Missing examples: 

List:
- text truncation
- text wrapping
- ~~disabled state for group header~~

Object list item:
- text/key attribute/title/status truncation

Display list item:
- label/text truncation

### PR DESCRIPTION
**Pull request by sKudum**
#### Please provide a link to the associated issue.

closes #4112 
closes #3487 

#### Please provide a brief summary of this pull request.
1).Added long text as requested to check accessibility with title.
2).Added unread in aria-label for screen readers.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

### CODE REVIEW

**Review by Betrozov — APPROVED** [review]

**Review by IlyaSurmay — APPROVED** [review]

File: apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-border-less-example.component.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export interface Movie {
 })
 export class PlatformDisplayListItemBorderLessExampleComponent {
     items: Movie[] = [
-        { title: 'Star War', secondary: 'Next session', navigationIndicator: true, link: '/platform/home' },
+        { title: 'Star War Item looooooooooooooooooooooooooooonoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong title', secondary: 'Next session Item looooooooooooooooooooooooooooonoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong message', navigationIndicator: true, link: '/platform/home' },
```
Comment (InnaAtanasova) [inline apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-border-less-example.component.ts:16]: I'd add `Lorem ipsum` text instead of this

Comment (sKudum) [reply apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-border-less-example.component.ts]: Hi @InnaAtanasova , Updated with Lorem ipsum text. Please do have a look.

**Review by InnaAtanasova — APPROVED** [review]

**Review by JKMarkowski — APPROVED** [review]
LGTM
