### PR TITLE
fix(core): correct breadcrumb overflow calculation

### LINKED ISSUE #8325: Breadcrumb overflowing incorrectly
In this screenshot you can see the breadcrumb item 4 overflowing the parent container, when in this example breadcrumb item 2 should be hidden and added to the overflow menu
Screen Shot 2022-07-05 at 12 32 12 PM

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue(s)

closes #8325 

## Description
Added menu container element width into calculation of free space.

### Before:
image

### After:
image

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

### CODE REVIEW

File: libs/core/src/lib/breadcrumb/breadcrumb.component.ts [hunk 1]
```diff
@@ -121,41 +127,47 @@ export class BreadcrumbComponent implements AfterViewInit, OnInit, OnDestroy {
...
+
+        if (this._overflowContainer) {
+            this._containerBoundary -= this._overflowContainer.nativeElement.getBoundingClientRect().width;
         }
 
         let visibleSum = 0;
-        const breadcrumbItemComponents = this.breadcrumbItems.toArray();
+        const breadcrumbItemComponents = this._breadcrumbItems.toArray();
         let i;
         for (i = breadcrumbItemComponents.length - 1; i >= 0; i--) {
```
Comment (platon-rov) [inline libs/core/src/lib/breadcrumb/breadcrumb.component.ts:150]: it looks like overflow layout algorithm, isn't it? could we use it here instead of having this code?

**Review by mikerodonnell89 — APPROVED** [review]
